RushHour.Web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RushHour.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using RushHour.Web.Models.RoleViewModels;
using Microsoft.AspNetCore.Authorization;

namespace RushHour.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<ApplicationUser> userManager;

        public RoleController(RoleManager<IdentityRole> roleMgr, UserManager<ApplicationUser> userMgr)
        {
            roleManager = roleMgr;
            userManager = userMgr;
        }

        public IActionResult Index()
        {
            return View(roleManager.Roles);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }

            return View(name);
        }

        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<ApplicationUser> members = new List<ApplicationUser>();
            List<ApplicationUser> nonMember = new List<ApplicationUser>();

            foreach (ApplicationUser user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name)
                    ? members
                    : nonMember;
                list.Add(user);
            }

            return View(new EditRoleViewModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMember
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ModifyRoleViewModel modifyRole)
        {
            IdentityResult result;

            if (ModelState.IsValid)
            {
                IdentityRole role = await roleManager.FindByIdAsync(modifyRole.RoleId);
                role.Name = modifyRole.RoleName;
                result = await roleManager.UpdateAsync(role);
                if (!result.Succeeded)
                {
                    AddErrors(result);
                }

                foreach (string userId in modifyRole.IdsToAdd ?? new string[] { })
                {
                    ApplicationUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user, modifyRole.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrors(result);
                        }
                    }
                }

                foreach (string userId in modifyRole.IdsToRemove ?? new string[] { })
                {
                    ApplicationUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.RemoveFromRoleAsync(user, modifyRole.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrors(result);
                        }
                    }
                }
            }

            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            return View(modifyRole.RoleId);
        }

        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);

            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }

            return View("Index", roleManager.Roles);
        }
    }
}

RushHour.Web/Views/Role/Create.cshtml
@model string

<div class="bg-primary panel-body">
    <h4>
        Create Role
    </h4>
</div>

<div class="text-danger" asp-validation-summary="All"></div>

<form method="post" asp-controller="Role" asp-action="Create" asp-antiforgery="true" class="form-horizontal">
    <div class="form-group">
        <label class="control-label col-sm-2" for="name">Name:</label>
        <div class="col-sm-4">
            <input class="form-control" name="name" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Create</button>
            <button type="reset" class="btn btn-primary">Reset</button>
            <a class="btn btn-primary" asp-controller="Role" asp-action="Index">Cancel</a>
        </div>
    </div>
</form>

RushHour.Web/Views/Role/Edit.cshtml
@using RushHour.Entities

@model RushHour.Web.Models.RoleViewModels.EditRoleViewModel

@{
    ViewData["Title"] = "Edit";
}

<div class="bg-primary panel-body">
    <h4>
        Edit Role
    </h4>
</div>

<div class="text-danger" asp-validation-summary="All"></div>

<form method="post" asp-controller="Role" asp-action="Edit" asp-antiforgery="true" class="form-horizontal">
    <input type="hidden" name="RoleId" value="@Model.Role.Id" />

    <div class="form-group">
        <label class="control-label col-sm-2" for="RoleName">Role Name:</label>
        <div class="col-sm-2">
            <input class="form-control" name="RoleName" value="@Model.Role.Name" />
        </div>
    </div>

    <h5 class="bg-info panel-body">
        Add to @Model.Role.Name
    </h5>
    <table class="table table-condensed table-bordered table-striped">
        @if (Model.NonMembers.Count() == 0)
        {
            <tr>
                <td colspan="2">All Users Are @Model.Role.Name</td>
            </tr>
        }
        else
        {
            foreach (ApplicationUser user in Model.NonMembers)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="IdsToAdd" value="@user.Id" />
                    </td>
                </tr>
            }
        }
    </table>

    <h5 class="bg-info panel-body">Remove from @Model.Role.Name</h5>
    <table class="table table-condensed table-bordered table-striped">
        @if (Model.Members.Count() == 0)
        {
            <tr>
                <td colspan="2">
                    No Users are @Model.Role.Name
                </td>
            </tr>
        }
        else
        {
            foreach (ApplicationUser user in Model.Members)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="IdsToRemove" value="@user.Id" />
                    </td>
                </tr>
            }
        }
    </table>

    <button type="submit" class="btn btn-primary">Save</button>
    <button type="reset" class="btn btn-primary">Reset</button>
    <a class="btn btn-primary" asp-controller="Role" asp-action="Index">Cancel</a>
</form>

RushHour.Web/Views/Role/Index.cshtml
@model IEnumerable<IdentityRole>

<div class="bg-primary panel-body">
    <h4>
        Roles
    </h4>
</div>

<div class="text-danger" asp-validation-summary="ModelOnly"></div>

<table class="table table-condensed table-bordered table-striped">
    <tr>
        <th>ID</th>
        <td>Name</td>
        <td></td>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="4" class="text-center">
                No roles
            </td>
        </tr>
    }
    else
    {
        foreach (var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>

                <td>
                    <a class="btn btn-sm btn-success" asp-controller="Role" asp-action="Edit" asp-route-id="@role.Id">
                        Edit
                    </a>
                    <a class="btn btn-sm btn-danger" asp-controller="Role" asp-action="Delete" asp-route-id="@role.Id">
                        Delete
                    </a>
                </td>
            </tr>
        }
    }
</table>

<a class="btn btn-primary" asp-controller="Role" asp-action="Create">
    Create
</a>
<a class="btn btn-primary" asp-controller="Home" asp-action="Index">
    Home
</a>